name: Pages

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Publish Pages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Doxygen
        uses: mattnotmitt/doxygen-action@v1

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
